### ISSUE TITLE
Please add support for OSX 10.15.2

### ISSUE THREAD

**Issue by MScuti** [AMD-OSX/AMD_Vanilla#80] opened 2019-12-11 10:41 UTC
If you have a support question, please go to the discord or the forum.

**Comment by XLNCs** [comment] 2019-12-11 14:44
support added !

**Comment by dhinakg** [comment] 2019-12-11 15:42
![image](https://user-images.githubusercontent.com/17605561/70636070-f25e4c80-1c02-11ea-9dee-388c933b3e3f.png)
Use the patch update template next time.

**Comment by surajmandalcell** [comment] 2019-12-20 03:23
Duplicate of #81

**Closed** 2020-01-07 03:06 UTC
Labels: patch update
